[project]
name = "auto-ibkr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ib-async==1.0.2",
    "nest-asyncio>=1.6.0",
]
